Adding zoxide init to bash_profile

diff --git a/bash-linux/.bash/utilities b/bash-linux/.bash/utilities
--- a/bash-linux/.bash/utilities
+++ b/bash-linux/.bash/utilities
@@ -1,12 +1,11 @@
 #!/usr/bin/env bash
 
 function repeat() {
-    n=$1
-    shift
-    while [ $(( n -= 1 )) -ge 0 ]
-    do
-        "$@"
-    done
+  n=$1
+  shift
+  while [ $((n -= 1)) -ge 0 ]; do
+    "$@"
+  done
 }
 
 # Sends a simple reminder
@@ -17,17 +16,16 @@ function messagereminder() {
 }
 
 function loadssh() {
-  if [ -z "$SSH_AUTH_SOCK" ] ; then
-    eval `ssh-agent -s`
+  if [ -z "$SSH_AUTH_SOCK" ]; then
+    eval $(ssh-agent -s)
     ssh-add
   fi
 }
 
 function getsslcert() {
-	host=$1
-	openssl s_client -connect $1 -showcerts
+  host=$1
+  openssl s_client -connect $1 -showcerts
 }
-
 
 function output-functions() {
   rg function ~/.bash
@@ -39,67 +37,69 @@ function output-functions() {
 # `less` with options to preserve color and line numbers, unless the output is
 # small enough for one screen.
 function tre() {
-	tree -aC -I '.git' --dirsfirst "$@" | less -FRNX
+  tree -aC -I '.git' --dirsfirst "$@" | less -FRNX
 }
 
 # Call from a local repo to open the repository on github/bitbucket in browser
 # Modified version of https://github.com/zeke/ghwd
 repo() {
-	# Figure out github repo base URL
-	local base_url
-	base_url=$(git config --get remote.origin.url)
-	base_url=${base_url%\.git} # remove .git from end of string
+  # Figure out github repo base URL
+  local base_url
+  base_url=$(git config --get remote.origin.url)
+  base_url=${base_url%\.git} # remove .git from end of string
 
-	# Fix git@github.com: URLs
-	base_url=${base_url//git@github\.com:/https:\/\/github\.com\/}
+  # Fix git@github.com: URLs
+  base_url=${base_url//git@github\.com:/https:\/\/github\.com\/}
 
-	# Fix git://github.com URLS
-	base_url=${base_url//git:\/\/github\.com/https:\/\/github\.com\/}
+  # Fix git://github.com URLS
+  base_url=${base_url//git:\/\/github\.com/https:\/\/github\.com\/}
 
-	# Fix git@bitbucket.org: URLs
-	base_url=${base_url//git@bitbucket.org:/https:\/\/bitbucket\.org\/}
+  # Fix git@bitbucket.org: URLs
+  base_url=${base_url//git@bitbucket.org:/https:\/\/bitbucket\.org\/}
 
-	# Fix git@gitlab.com: URLs
-	base_url=${base_url//git@gitlab\.com:/https:\/\/gitlab\.com\/}
+  # Fix git@gitlab.com: URLs
+  base_url=${base_url//git@gitlab\.com:/https:\/\/gitlab\.com\/}
 
-	# Validate that this folder is a git folder
-	if ! git branch 2>/dev/null 1>&2 ; then
-		echo "Not a git repo!"
-		exit $?
-	fi
+  # Validate that this folder is a git folder
+  if ! git branch 2>/dev/null 1>&2; then
+    echo "Not a git repo!"
+    exit $?
+  fi
 
-	# Find current directory relative to .git parent
-	full_path=$(pwd)
-	git_base_path=$(cd "./$(git rev-parse --show-cdup)" || exit 1; pwd)
-	relative_path=${full_path#$git_base_path} # remove leading git_base_path from working directory
+  # Find current directory relative to .git parent
+  full_path=$(pwd)
+  git_base_path=$(
+    cd "./$(git rev-parse --show-cdup)" || exit 1
+    pwd
+  )
+  relative_path=${full_path#$git_base_path} # remove leading git_base_path from working directory
 
-	# If filename argument is present, append it
-	if [ "$1" ]; then
-		relative_path="$relative_path/$1"
-	fi
+  # If filename argument is present, append it
+  if [ "$1" ]; then
+    relative_path="$relative_path/$1"
+  fi
 
-	# Figure out current git branch
-	# git_where=$(command git symbolic-ref -q HEAD || command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
-	git_where=$(command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
+  # Figure out current git branch
+  # git_where=$(command git symbolic-ref -q HEAD || command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
+  git_where=$(command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
 
-	# Remove cruft from branchname branch=${git_where#refs\/heads\/} 
-	[[ $base_url == *bitbucket* ]] && tree="src" || tree="tree"
-	url="$base_url/$tree/$branch$relative_path"
+  # Remove cruft from branchname branch=${git_where#refs\/heads\/}
+  [[ $base_url == *bitbucket* ]] && tree="src" || tree="tree"
+  url="$base_url/$tree/$branch$relative_path"
 
+  echo "Calling $(type open) for $url"
 
-	echo "Calling $(type open) for $url"
-
-	open "$url" &> /dev/null || (echo "Using $(type open) to open URL failed." && exit 1);
+  open "$url" &>/dev/null || (echo "Using $(type open) to open URL failed." && exit 1)
 }
 
 function nvminit {
-    export NVM_DIR="$HOME/.nvm"
-    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" #This loads nvm
-    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" #This loads nvm bash_completion
+  export NVM_DIR="$HOME/.nvm"
+  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   #This loads nvm
+  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" #This loads nvm bash_completion
 }
 
 function findtodos {
- rg "\[ \]"
+  rg "\[ \]"
 }
 
 # From https://stackoverflow.com/questions/23070245/get-all-files-modified-in-last-30-days-in-a-directory
@@ -118,6 +118,13 @@ function bat-allfilesrecursively {
 }
 
 function timer() {
-    n=$1
-		countdown "$n" && hs -c 'displayMessageOnAllScreens("Timer is done", 10)'
+  n=$1
+  countdown "$n" && hs -c 'displayMessageOnAllScreens("Timer is done", 10)'
 }
+
+zoxide_refresh_src() {
+  # adjust depth if you want to include nested projects
+  find ~/src -maxdepth 1 -type d -print0 | xargs -0 zoxide add
+}
+
+alias zrs='zoxide_refresh_src' # quick manual refresh
